apiVersion: v1
kind: PersistentVolume
metadata:
  name: tickets-mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/rooster/test/mongo/tickets-mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-mongo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
